Update code for HPA with custom metric
Schub-cloud/helm-charts pull request #11
Opened 2023-01-07 07:25 UTC by faisaljogo

2023-01-09 19:46 UTC, jfmrm requested changes

2023-01-09 19:46 UTC, jfmrm commented on application/templates/hpa.yaml
> +    {{- if .Values.autoscaling.renable_rabbitmq_custom_metric }}
although rabbitmq should be the metric for we to test the template with this template should be generic enough for we to setup any matric we need.

2023-01-09 19:46 UTC, jfmrm commented on application/values.yaml
> +  enable_rabbitmq_custom_metric: false
to make this generic we could define the values.yaml in a different way here:
```suggestion
  customMetrics:
    metricName:
      describedObject:
        ...
      target:
        ...
```

2023-01-09 19:46 UTC, jfmrm commented on application/templates/hpa.yaml
> +          name: rabbitmq_queue_messages
this parameter should not be hardcoded.

2023-01-09 19:46 UTC, jfmrm commented on application/templates/hpa.yaml
> +          kind: Service
these should not be hardcoded

2023-01-11 17:10 UTC, jfmrm requested changes

2023-01-11 17:10 UTC, jfmrm commented on application/values.yaml
> +      value: ""
`customMetrics` should be a map so we can add multiple metrics, also the `enabled` should not be needed, since when we use loops within a `with` clause in helm it doesn't render anything in case the object it's iterating over is empty.

The values part should look somewhat like this.
```suggestion
  customMetrics:
    metricA:
      describedObject:
        apiVersion: ""
        kind: ""
        name: ""
      target:
        value: ""
    metricB:
      describedObject:
        apiVersion: ""
        kind: ""
        name: ""
      target:
        value: ""
```

2023-01-11 17:10 UTC, jfmrm commented on application/templates/hpa.yaml
> +    {{- end }}
this piece should be iterative in order to generate template for any number of custom metrics, and render nothing if it's empty.

2023-01-13 13:27 UTC, faisaljogo commented on application/values.yaml
> +      value: ""
I have tried different approach let me know if it looks good to you.?

Thanks

2023-01-13 17:33 UTC, jfmrm commented on application/values.yaml
> +      value: ""
@faisaljogo, I saw that you used a list instead of a map. The problem with this is that we use multiple values when composing a multi-environment setup.yaml files to achieve the configuration without repeating ourselves.

Helm will merge as many files as you pass to it, but lists are not merged; the one that stays is the last. This is really annoying to deal with, and that is why I'm stressing about keeping lists to the bare minimum.

check this out: https://stackoverflow.com/questions/64824694/helm-how-to-iterate-over-map-with-complex-values

2023-01-16 07:06 UTC, faisaljogo commented on application/values.yaml
> +      value: ""
I have made the changes

2023-01-16 12:44 UTC, jfmrm requested changes

2023-01-16 12:44 UTC, jfmrm commented on application/values.yaml
> +        value: ""
comment these values so by default there is no custom metric. But keep them commented so it stays as example.

2023-01-16 12:45 UTC, jfmrm commented
Also, have u tested the functionality by installing the helm chart in the cluster?

2023-01-16 16:02 UTC, faisaljogo commented
> Also, have u tested the functionality by installing the helm chart in the cluster?

yes I have tested it

2023-01-16 16:02 UTC, faisaljogo commented on application/values.yaml
> +        value: ""
I will do it

2023-01-16 17:51 UTC, jfmrm requested changes
sorry, some stuff that I didn't caught before.

2023-01-16 17:51 UTC, jfmrm commented on application/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta2
this API version should be `autoscaling/v2`

2023-01-16 17:51 UTC, jfmrm commented on application/templates/hpa.yaml
> +          type: Value
this should not be hard coded.

2023-01-16 17:51 UTC, jfmrm commented on application/templates/hpa.yaml
> +          type: AverageValue
this should not be hard coded.

2023-01-17 05:20 UTC, faisaljogo commented on application/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta2
type: Object 
is not in autoscaling/v2

2023-01-17 05:20 UTC, faisaljogo commented on application/templates/hpa.yaml
> +          type: AverageValue
sure I will update it

2023-01-17 13:02 UTC, jfmrm requested changes

2023-01-17 13:02 UTC, jfmrm commented on application/templates/hpa.yaml
>      {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
this conditional will be always false since u have changed the structure of the autoscaling object.
remember we should be able to disable memory and cpu utilization. Maybe if we use `.Values.autoscaling.memory` for this conditional we can make this work, but we will need to leave the default value of the memory directive empty by default, which can be achieved by commenting the valeus in the values.yaml file.

The same comment also applies to cpu metric.

2023-01-17 13:02 UTC, jfmrm commented on application/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta2
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec

From what I can see in the API reference it is there. The reason we should use v2 is because beta versions are not stable, so we should not use it if it's not 100% necessary.

2023-01-17 16:15 UTC, faisaljogo commented on application/templates/hpa.yaml
>      {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
I will try to update the HPA for version v2

2023-01-18 17:53 UTC, jfmrm approved these changes

2023-01-18 17:56 UTC, merged