feat: add Reloader 'auto' and 'custom' options
Schub-cloud/helm-charts pull request #14
Opened 2023-01-12 16:25 UTC by hugo-calado

Modify values.yaml and _helpers.tpl to add Reloader options of "auto" and "custom" to restart deployment upon configmap/secret change.

2023-01-12 16:26 UTC, hugo-calado commented
Working now in validating directly on k8s cluster.

2023-01-12 20:43 UTC, hugo-calado commented
Finished validation of this PR.

Created specific namespace, then created generic configmap:
![image](https://user-images.githubusercontent.com/120131620/212174815-0951954a-d44f-45ba-9d93-17d1351105d7.png)

Installed Reloader and helm application (autorestart):
![image](https://user-images.githubusercontent.com/120131620/212175086-ddef1a25-40ff-4785-81d2-9806cd890551.png)

Verified deployment has correct annotation:
![image](https://user-images.githubusercontent.com/120131620/212175929-ac381750-628b-4024-9413-559860cda91e.png)

Validated that, altering the value of the configmap triggers the creation of new pod with update value:
![image](https://user-images.githubusercontent.com/120131620/212176348-45809651-bb91-4819-85dc-b962e68c8a08.png)

2023-01-13 17:17 UTC, jfmrm requested changes
looks good, liked the approach on the annotations in the helpers.

2023-01-13 17:17 UTC, jfmrm commented on application/values.yaml
> +reloader:
add `enabled` option default to false.

2023-01-13 17:17 UTC, jfmrm commented on application/values.yaml
> +  auto: false
default this to true, so if it's enabled it will add auto reload by default.

2023-01-13 17:17 UTC, jfmrm commented on application/values.yaml
> +    #values:
can we remove the values node? seems kinda useless semantically.

2023-01-13 21:04 UTC, hugo-calado commented
Validation after new changes applied.

## AUTO

Confirmed annotation is being placed correctly on deployment:
![image](https://user-images.githubusercontent.com/120131620/212415128-38a5c735-9ef5-4cad-9a28-5e9e9cec4426.png)


Validated after changing configmap the deployment gets automatically restarted:
![image](https://user-images.githubusercontent.com/120131620/212414889-b702f422-93fa-4cfd-8156-742a3d66fe0b.png)

The same behaviour happens when using secrets:
![image](https://user-images.githubusercontent.com/120131620/212417172-a33e39ff-0945-459a-bb38-4509a5b736c8.png)

## CUSTOM
Validated annotations got placed correctly:
![image](https://user-images.githubusercontent.com/120131620/212417796-a74b5bfb-5fc5-4ed3-ac68-a84601ffb0bc.png)

Changes on secret 'mysecret' trigger a restart:
![image](https://user-images.githubusercontent.com/120131620/212418162-8ce22cd7-1751-468f-99a7-4cf18a35eb74.png)

As well as changes on the configmap 'log-config':
![image](https://user-images.githubusercontent.com/120131620/212418391-7df05f14-9b8b-4e7d-b4f3-70e1a8e0fb89.png)

2023-01-16 17:52 UTC, jfmrm approved these changes

2023-01-16 19:39 UTC, merged