feat: update deployment and value files
Schub-cloud/helm-charts pull request #7
Opened 2022-12-26 18:29 UTC by hugocalad0

PR to add feature of custom livenessProbe and readinessProbe.

2022-12-27 15:15 UTC, jfmrm requested changes

2022-12-27 15:15 UTC, jfmrm commented on application/values.yaml
> +    probe:
looks good, but disable probes by default and put these examples as comments.

2022-12-28 17:25 UTC, hugocalad0 commented on application/values.yaml
> +    probe:
@jfmrm changes applied.

2023-01-02 12:59 UTC, jfmrm commented
@hugo-calado looks good now, just 2 small things.
1. mind commit messages, they should be descriptive regarding the content of the PR and follow the pattern, this will be useful to maintain automatic version tagging soon.
2. have u tested the code? I mean run helm install and try to spin up a test application in our experiments cluster? Could u post some prints on the PR to show it's working?

2023-01-03 20:20 UTC, hugo-calado commented
Finished validation of this PR.

Created specific namespace, then installed helm application:
![image](https://user-images.githubusercontent.com/120131620/210433326-8d3a971d-9d6c-41b1-b018-6721ae2a7798.png)

For this validation, it was used the image and probes directly from kubernetes documentation (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe).

Probes configured on values.yaml file:
![image](https://user-images.githubusercontent.com/120131620/210434737-1d85ff97-fd25-42b1-bdd8-40d5983aaed4.png)


Were able to validate that both liveness and readiness probes were applied successfully and were working as expected:
![image](https://user-images.githubusercontent.com/120131620/210434697-72309631-f716-4751-bb22-c44d38fcc839.png)

2023-01-09 19:58 UTC, jfmrm approved these changes

2023-01-09 20:08 UTC, merged