feat: mountable confgimap and secrets
Schub-cloud/helm-charts pull request #8
Opened 2022-12-27 12:39 UTC by hugocalad0

PR to add feature of customizable mount of configmap and/or secrets.

2022-12-27 13:40 UTC, jfmrm requested changes

2022-12-27 13:40 UTC, jfmrm commented on application/values.yaml
> +      mountPath: /etc/config
change this to a map, take the name as the key.
instead of:
```
volumes: 
  - volume: name
```
do:
```
volumes:
  name:
    config:
```

2022-12-28 17:30 UTC, hugocalad0 commented on application/values.yaml
> +      mountPath: /etc/config
@jfmrm changes applied.

2023-01-02 13:02 UTC, jfmrm commented
@hugo-calado looks good now, just 2 small things.
1. mind commit messages, they should be descriptive regarding the content of the PR and follow the pattern, this will be useful to maintain automatic version tagging soon.
2. have u tested the code? I mean run helm install and try to spin up a test application in our experiments cluster? Could u post some prints on the PR to show it's working?

2023-01-03 14:41 UTC, hugo-calado commented
Finished validation of this PR.

Created specific namespace, then created generic configmap and secret:
![image](https://user-images.githubusercontent.com/120131620/210378612-734ee8b0-d32c-410a-83bf-61ff17aec567.png)

Installed app:
![image](https://user-images.githubusercontent.com/120131620/210378704-eca38ab3-4e5b-426b-94df-0b8e2013341e.png)

Finally, validated that configmap and secret were mounted on pod:
![image](https://user-images.githubusercontent.com/120131620/210378925-3ce27806-4aa5-4472-a4ae-783cd1cc2ee3.png)

2023-01-09 19:56 UTC, jfmrm approved these changes

2023-01-09 20:08 UTC, merged